nolnol/config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'myboard/index' => 'myboard#index'
  get 'myboard/index2' => 'myboard#index2'

  get 'jujum/index'
  get 'jujum/num2'
  get 'jujum/num3'
  get 'jujum/num4'
  get 'jujum/num5'
  get 'jujum/num6'
  get 'jujum/num7'
  get 'jujum/num8'
  get 'jujum/num9'
  get 'jujum/num10'
  resources :boards
  get "/user" => "errorstation#emailover"
  post '/boards/:board_id' =>"boards#comment"

  get 'followlist/' => 'followlist#index'
  get '/agree' =>"agree#index"
  get '/watching_people' => 'watching_people#index'
  get '/line_up' => 'line_up#index'
  get '/my_profile' => 'my_profile#index'
  get 'info_page/' => 'info_page#index'
  get 'chat_rooms/' => 'chat_rooms#index'
  resources :chat_rooms, only: [:new, :create, :show, :index]
  resources :follows, only: [:create, :destroy]

  # mailbox folder routes
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  ## devise controllers for users
  devise_for :user, controllers: {
    # confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    # unlocks: 'users/unlocks',
  }, skip: [:sessions]

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
  ## custom routes for users
  as :user do
    get 'login' => 'users/sessions#new', as: :new_user_session
    post 'login' => 'users/sessions#create', as: :user_session
    get 'logout' => 'users/sessions#destroy',to: redirect('/login'), as: :destroy_user_session
    get 'register' => 'users/registrations#new'
    get 'profile_edit' => 'users/registrations#edit'
  end
end

nolnol/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

      can :create, Board
      can :read, Board
      can :update, Board do |board|
        board.user == user
      end

      can :delete, Board do |board|
        board.user == user
      end
	
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

nolnol/app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

nolnol/app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  mount_uploader :board_image, S3Uploader
end

nolnol/app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
end

nolnol/app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :board
end

nolnol/app/models/follow.rb
class Follow < ApplicationRecord
	# 팔로우 신청한 유저
  # 관계 이름 : follower
  # 모델 명 : User
  belongs_to :follower, class_name: "User"

  # 팔로우 신청 받은 유저
  # 관계 이름 : followed
  # 모델 명 : User
  belongs_to :followed, class_name: "User"
end

nolnol/app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room

  validates :body, presence: true, length: {minimum: 2, maximum: 1000}

  after_create_commit { MessageBroadcastJob.perform_later(self) }

  def timestamp
    created_at.strftime('%H:%M:%S %d %B %Y')
  end
end

nolnol/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :boards, dependent: :destroy
  has_many :comments, dependent: :destroy
  acts_as_messageable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :image, S3Uploader
  def mailboxer_name
    self.user_name
  end

  def mailboxer_email(object)
    self.email
  end
  validates :user_name, presence: true, uniqueness: false
  # 관계 이름 : follower_relations(다른 이름으로 변경 가능)
  # 외래키 : followed_id
  # 모델명 : Follow
  has_many :follower_relations, foreign_key: "followed_id", class_name: "Follow"
  # 관계 이름 : followers (다른 이름으로 변경 가능)
  # follow_relations를 통해 가져올 값 : follower ( follow.follower )
  has_many :followers, through: :follower_relations, source: :follower

  has_many :follower_relations, foreign_key: "followed_id", class_name: "Follow"
  has_many :followers, through: :follower_relations, source: :follower

  has_many :following_relations, foreign_key: "follower_id", class_name: "Follow"
  has_many :followings, through: :following_relations, source: :followed
end

nolnol/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  
  end
end

nolnol/app/controllers/watching_people_controller.rb
class WatchingPeopleController < ApplicationController
  def index
    @users = user_scope.paginate(page: params[:page], per_page: 10).order("users.current_sign_in_at DESC")
  end

  private

  def user_scope
    current_user ? User.where.not(id: current_user.id) : User.all
  end
end

nolnol/app/helpers/agree_helper.rb
module AgreeHelper
end

nolnol/app/helpers/application_helper.rb
module ApplicationHelper
	def active_page(active_page)
    @active == active_page ? "active" : ""
  end
	def gravatar_for(user, opts = {})
    opts[:alt] = user.name
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?s=#{opts.delete(:size) { 40 }}",
              opts
  end
end

nolnol/app/helpers/boards_helper.rb
module BoardsHelper
end

nolnol/app/helpers/followlist_helper.rb
module FollowlistHelper
end

nolnol/app/helpers/follows_helper.rb
module FollowsHelper
end

nolnol/app/helpers/info_page_helper.rb
module InfoPageHelper
end

nolnol/app/helpers/jujum_helper.rb
module JujumHelper
end

nolnol/app/helpers/line_up_helper.rb
module LineUpHelper
end

nolnol/app/helpers/mailbox_helper.rb
module MailboxHelper
  def unread_messages_count
    # how to get the number of unread messages for the current user
    # using mailboxer
    mailbox.inbox(unread: true).count
  end
end

nolnol/app/helpers/my_profile_helper.rb
module MyProfileHelper
end

nolnol/app/helpers/myboard_helper.rb
module MyboardHelper
end

nolnol/app/helpers/watching_people_helper.rb
module WatchingPeopleHelper
end

nolnol/app/views/watching_people/index.html.erb
<div class="container-fluid">
  <%= render partial: 'home/navbar' %>
  <%= render partial: 'home/banner' %>
    <div class="colortotitle">
      <h3 class="bigex2">사람구경하기 </h3>
      <p class="smallex">마음에 드는 사람에게 하트를 날려보세요!</p>
      <p class="smallex">하트를 받은 상대방이 답장을 보내면,</p>
      <p class="smallex"><a href="/mailbox/inbox">메시지함</a>에서 상대에게 메시지를 보낼 수 있습니다</p>
      <p class="smallex"><a href="/my_profile">내 프로필</a>에서 <a href="/followlist">호감을 준 사람</a>을 체크하세요!</p>
      <br>
      </div>  
  <div class="container" style="text-align:center; ">
        <p style="color:grey; margin-top:10px;margin-left:5px; text-align:left;">전체 회원수 : <%= @ucount=User.all.length %> </p>
      <% @users.each do |user| %>
      <div class="col-md-4 col-md-offset-4 profile_obj">
        <div class="user_image" id="myImg">
					<%= image_tag("#{user.image}", class:"imageClass") %>
				</div>
				<!-- The Modal -->
				<div id="myModal" class="modal">
					<%= image_tag("#{user.image}", id:"modal_img") %>
  			<!-- The Close Button -->
  			<span class="close" onclick="document.getElementById('myModal').style.display='none'">&times;</span>
			</div>
       <span class="profile_content"><%= user.user_name %> |</span>
        <span class="profile_content"><%= user.user_age %>살 |</span>
        <span class="profile_content"><%= user.user_gender %> |</span>
        <span class="profile_content"><%= user.user_state %></span>
        <span class="like-button">
          <% if user_signed_in? && current_user.id == user.id%>
         	| 본인
         	<% end%>
          <% if user_signed_in? && current_user.id != user.id%>
            <% if current_user.followings.include?(user) %>

              <%= form_tag follow_path(user.id), method: :delete, class: "right" do %>
                <button class="btn btn-warning">취소할래요 <i class="glyphicon glyphicon-remove"></i></button>
                  <% end %>

                  <% else %>

                  <%= form_tag follows_path, class:"right" do %>
                   <input type="hidden" name="followed_id" value="<%= user.id %>" />
                   <button class="btn btn-danger">마음에 들어요 <i class="glyphicon glyphicon-heart"></i></button>
               	  <% end %>

              <% end %>
          <% end %>
        </span>
      </div>
      <% end %>
    </div>
    <div class="container">
        <nav aria-label="Page navigation" class="main-pagination">
          <ul class="pagination">
            <li><%= will_paginate @users, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, :class => "other_profile" %></li>
          </ul>
        </nav>
    </div>

<style>
	h5{
		text-align:center;
		color:#776969;
		font-weight:bold;
	}
  .colortotitle{
    background-color:#fcf4f4;
    width:100%;
    padding-top:0px;
  }
	.bigex2{
	  margin-top:0px;
	  padding-top:20px;
	  font-weight:bold;
	  text-align:center;
	  color:#ee4065;
	}
		.smallex{
	  margin-top:3px;
	  margin-bottom:3px;
	  font-size:12px;
	  text-align:center;
	  color:gray;
	}	
.profile_intro > p{
  color:white;
  font-size:15px;
  text-align: center;
}

.user_image img {
  float: none;
  margin: 0 auto;
  width: 240px;
  height: 240px;
  #circle
  -webkit-clip-path: circle(100px at 50% 50%);
  clip-path: circle(100px at 50% 50%);
}

h3 		 {
  font-size: 25px;
  text-align:center;
  margin-top: 20px;
  margin-bottom: 10px;
  color:#ee4065;
}
.profile_obj{
  border:1px solid rgb(230, 219, 219);
  padding-bottom: 30px;
  padding-top:10px;
  margin: 20px 0px 20px 0px;
  background-color: rgba(255, 219, 220,0.5);
  border-radius: 15px;
}
.main-pagination{
  text-align:center;
  margin-bottom:20px;
}
.profile_content{
  text-align:center;
}

.other_profile .page-link{
  color: gray;
  text-decoration:none;
  border:0;
  background-color:white;
  font-size:22px;
}

.other_profile .active .page-link{
  color:orange!important;
  background-color:white;
  border-bottom:2px solid orange;

}
.other_profile a:hover{
  color:orange!important;
  background-color:white!important;
}
form.right{
  margin-top: 15px;
}
nav.main-pagination{
  height:100px;
}
.modal {
    display: none; /* Hidden by default */
		text-align: center;
    position: fixed; /* Stay in place */
    z-index: 4; /* Sit on top */
    padding-top: 100px; /* Location of the box */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.9); /* Black w/ opacity */
}

/* Modal Content (Image) */
.modal-content {
    margin: auto;
    display: block;
    width: 80%;
    max-width: 700px;
}
/* The Close Button */
.close {
    position: absolute;
    top: 15px;
    right: 35px;
    color: white;
    font-size: 40px;
    font-weight: bold;
    transition: 0.3s;
}

.close:hover,
.close:focus {
    color: white;
    text-decoration: none;
    cursor: pointer;
}

/* 100% Image Width on Smaller Screens */
@media only screen and (max-width: 700px){
    .modal-content {
        width: 100%;
    }
/* unvisited link */
.smallex a:link {
    color: #fc92ac;
}

/* visited link */
.smallex a:visited {
    color: #ee4065;
}

/* mouse over link */
.smallex a:hover {
    color: #ee4065;
    font-weight:bold;
    text-decoration: none;
}

/* selected link */
 .smallex a:active {
    color: #ffdbdc;
}
}
</style>
<script>



	// Get the modal
	var modal = document.getElementById('myModal');
  var images = document.getElementsByClassName("imageClass");

	// Get the image and insert it inside the modal - use its "alt" text as a caption
	//var img = document.getElementById('myImg');
  for(var i = 0; i < images.length; i++){
    var img = images[i];
  	var modalImg = document.getElementById("modal_img");
  	img.onclick = function(){
  		modal.style.display = "block";
  		modalImg.src = this.src;
  	  }
    }

	// Get the <span> element that closes the modal
	var span = document.getElementsByClassName("close")[0];

	// When the user clicks on <span> (x), close the modal
	span.onclick = function() {
	modal.style.display = "none";
	}
</script>