nolnol/config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'myboard/index' => 'myboard#index'
  get 'myboard/index2' => 'myboard#index2'

  get 'jujum/index'
  get 'jujum/num2'
  get 'jujum/num3'
  get 'jujum/num4'
  get 'jujum/num5'
  get 'jujum/num6'
  get 'jujum/num7'
  get 'jujum/num8'
  get 'jujum/num9'
  get 'jujum/num10'
  resources :boards
  get "/user" => "errorstation#emailover"
  post '/boards/:board_id' =>"boards#comment"

  get 'followlist/' => 'followlist#index'
  get '/agree' =>"agree#index"
  get '/watching_people' => 'watching_people#index'
  get '/line_up' => 'line_up#index'
  get '/my_profile' => 'my_profile#index'
  get 'info_page/' => 'info_page#index'
  get 'chat_rooms/' => 'chat_rooms#index'
  resources :chat_rooms, only: [:new, :create, :show, :index]
  resources :follows, only: [:create, :destroy]

  # mailbox folder routes
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  ## devise controllers for users
  devise_for :user, controllers: {
    # confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    # unlocks: 'users/unlocks',
  }, skip: [:sessions]

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
  ## custom routes for users
  as :user do
    get 'login' => 'users/sessions#new', as: :new_user_session
    post 'login' => 'users/sessions#create', as: :user_session
    get 'logout' => 'users/sessions#destroy',to: redirect('/login'), as: :destroy_user_session
    get 'register' => 'users/registrations#new'
    get 'profile_edit' => 'users/registrations#edit'
  end
end

nolnol/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

      can :create, Board
      can :read, Board
      can :update, Board do |board|
        board.user == user
      end

      can :delete, Board do |board|
        board.user == user
      end
	
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

nolnol/app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

nolnol/app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  mount_uploader :board_image, S3Uploader
end

nolnol/app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
end

nolnol/app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :board
end

nolnol/app/models/follow.rb
class Follow < ApplicationRecord
	# 팔로우 신청한 유저
  # 관계 이름 : follower
  # 모델 명 : User
  belongs_to :follower, class_name: "User"

  # 팔로우 신청 받은 유저
  # 관계 이름 : followed
  # 모델 명 : User
  belongs_to :followed, class_name: "User"
end

nolnol/app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room

  validates :body, presence: true, length: {minimum: 2, maximum: 1000}

  after_create_commit { MessageBroadcastJob.perform_later(self) }

  def timestamp
    created_at.strftime('%H:%M:%S %d %B %Y')
  end
end

nolnol/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :boards, dependent: :destroy
  has_many :comments, dependent: :destroy
  acts_as_messageable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :image, S3Uploader
  def mailboxer_name
    self.user_name
  end

  def mailboxer_email(object)
    self.email
  end
  validates :user_name, presence: true, uniqueness: false
  # 관계 이름 : follower_relations(다른 이름으로 변경 가능)
  # 외래키 : followed_id
  # 모델명 : Follow
  has_many :follower_relations, foreign_key: "followed_id", class_name: "Follow"
  # 관계 이름 : followers (다른 이름으로 변경 가능)
  # follow_relations를 통해 가져올 값 : follower ( follow.follower )
  has_many :followers, through: :follower_relations, source: :follower

  has_many :follower_relations, foreign_key: "followed_id", class_name: "Follow"
  has_many :followers, through: :follower_relations, source: :follower

  has_many :following_relations, foreign_key: "follower_id", class_name: "Follow"
  has_many :followings, through: :following_relations, source: :followed
end

nolnol/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  
  end
end

nolnol/app/controllers/mailbox_controller.rb
class MailboxController < ApplicationController
	before_action :authenticate_user!

  def inbox
    @inbox = mailbox.inbox
    @active = :inbox
		unless !user_signed_in?
    	@followedall = current_user.followers.all
    	@followingall = current_user.followings.all
    end
  end

  def sent
    @sent = mailbox.sentbox
    @active = :sent
  end

  def trash
    @trash = mailbox.trash
    @active = :trash
  end

end

nolnol/app/helpers/agree_helper.rb
module AgreeHelper
end

nolnol/app/helpers/application_helper.rb
module ApplicationHelper
	def active_page(active_page)
    @active == active_page ? "active" : ""
  end
	def gravatar_for(user, opts = {})
    opts[:alt] = user.name
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?s=#{opts.delete(:size) { 40 }}",
              opts
  end
end

nolnol/app/helpers/boards_helper.rb
module BoardsHelper
end

nolnol/app/helpers/errorstation_helper.rb
module ErrorstationHelper
end

nolnol/app/helpers/followlist_helper.rb
module FollowlistHelper
end

nolnol/app/helpers/follows_helper.rb
module FollowsHelper
end

nolnol/app/helpers/info_page_helper.rb
module InfoPageHelper
end

nolnol/app/helpers/jujum_helper.rb
module JujumHelper
end

nolnol/app/helpers/line_up_helper.rb
module LineUpHelper
end

nolnol/app/helpers/mailbox_helper.rb
module MailboxHelper
  def unread_messages_count
    # how to get the number of unread messages for the current user
    # using mailboxer
    mailbox.inbox(unread: true).count
  end
end

nolnol/app/helpers/my_profile_helper.rb
module MyProfileHelper
end

nolnol/app/helpers/myboard_helper.rb
module MyboardHelper
end

nolnol/app/views/mailbox/_folder_view.html.erb
<div class="container-fluid">
  <%= render partial: 'home/navbar' %>
  <%= render partial: 'home/banner' %>
 <br>
 <div class="container">
 <div class="row">
  <div class="col-md-6">
    <%= link_to "새 메시지", new_conversation_path, class: "btn btn-info" %>
    <%= link_to "새로고침", mailbox_inbox_path, class: "btn btn-warning pull-right" %>
  </div>
  </div>
  <br>
</div>
  <div class="col-md-4">

    <div class="panel panel-default">
      <div class="panel-body">
          <%= render 'mailbox/folders' %>
      </div>
    </div>
  </div>

  <div class="col-md-8">
    <div class="overflower2">
    <div class="panel panel-default">
      <div class="panel-body">
        <% if is_conversation %>
          <%= render 'conversations/form' %>
        <% else %>
            <%= render partial: 'conversations/conversation', collection: messages %>
            <% unless messages.any? %>
              <%= image_tag "no_message.png",id:"no_mess" %>
              <p style="color:#585858;">아직까지 받은 메시지가 없어요~ㅠ</p>
            <% end %>
        <% end %>
      </div>
    </div>
    <br><br><br><br>
    <br><br><br><br>
  </div>
</div>
</div>
</div>
<br>
<style>
  .overflower2{max-height:400px;  overflow-y:scroll;}
  .btn-info{
    background-color: #ec8c8f;
    border-color: #ec8c8f;
  }
  .btn-warning{
    background-color: #ec8c8f;
    border-color: #ec8c8f;
  }
  .panel-body{
    text-align: center;
  }
  #no_mess{
    width: 100px;
    height: 100px;
  }
</style>

nolnol/app/views/mailbox/_folders.html.erb
<ul class="nav nav-pills nav-stacked">
  <li class="<%= active_page(:inbox) %>">
    <%= link_to mailbox_inbox_path do  %>
        <span class="label label-danger pull-right" ><%=unread_messages_count%></span>
        <em class="fa fa-inbox fa-lg"></em>
        <span style="margin-left:30px;">받은 메시지</span>
    <% end %>
  </li>
  <li class="<%= active_page(:sent) %>">
    <%= link_to mailbox_sent_path do %>
        <em class="fa fa-paper-plane-o fa-lg"></em>
        <span style="margin-left:10px;">보낸 메시지</span>
    <% end %>
  </li>

  <!--<li class="<%= active_page(:trash) %>">
    <%= link_to mailbox_trash_path do %>
        <em class="fa fa-trash-o fa-lg"></em>
        <span>쓰레기통</span>
    <% end %>
  </li>-->
</ul>
<style>
.nav-pills > li.active > a, .nav-pills > li.active > a:hover, .nav-pills > li.active > a:focus{
	background-color: #f45e62;
}
.nav>li>a{
	color:#f45e62;
}
</style>

nolnol/app/views/mailbox/inbox.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @inbox } %>

nolnol/app/views/mailbox/sent.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @sent } %>

nolnol/app/views/mailbox/trash.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @trash } %>