sudoku/config/routes.rb
Rails.application.routes.draw do
  resources :contries
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

sudoku/app/models/contry.rb
class Contry < ApplicationRecord
end

sudoku/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception
end

sudoku/app/controllers/contries_controller.rb
class ContriesController < ApplicationController
  before_action :set_contry, only: [:show, :edit, :update, :destroy]

  # GET /contries
  # GET /contries.json
  def index
    @contries = Contry.all
  end

  # GET /contries/1
  # GET /contries/1.json
  def show
  end

  # GET /contries/new
  def new
    @contry = Contry.new
  end

  # GET /contries/1/edit
  def edit
  end

  # POST /contries
  # POST /contries.json
  def create
    @contry = Contry.new(contry_params)

    respond_to do |format|
      if @contry.save
        format.html { redirect_to @contry, notice: 'Contry was successfully created.' }
        format.json { render :show, status: :created, location: @contry }
      else
        format.html { render :new }
        format.json { render json: @contry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contries/1
  # PATCH/PUT /contries/1.json
  def update
    respond_to do |format|
      if @contry.update(contry_params)
        format.html { redirect_to @contry, notice: 'Contry was successfully updated.' }
        format.json { render :show, status: :ok, location: @contry }
      else
        format.html { render :edit }
        format.json { render json: @contry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contries/1
  # DELETE /contries/1.json
  def destroy
    @contry.destroy
    respond_to do |format|
      format.html { redirect_to contries_url, notice: 'Contry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contry
      @contry = Contry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contry_params
      params.require(:contry).permit(:continent, :cont_image, :cont_name, :center, :pop, :area, :money, :lang, :religion)
    end
end

sudoku/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @contry = Contry.order("RANDOM()").first
  end
end

sudoku/app/helpers/contries_helper.rb
module ContriesHelper
end

sudoku/app/views/contries/_form.html.erb
<div class="container">
<%= form_with(model: contry, local: true) do |form| %>
  <% if contry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contry.errors.count, "error") %> prohibited this contry from being saved:</h2>

      <ul>
      <% contry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :continent %>
    <%= form.text_field :continent, id: :contry_continent %>
  </div>

  <div class="field">
    <%= form.label :cont_image %>
    <%= form.text_field :cont_image, id: :contry_cont_image %>
  </div>

  <div class="field">
    <%= form.label :cont_name %>
    <%= form.text_field :cont_name, id: :contry_cont_name %>
  </div>

  <div class="field">
    <%= form.label :center %>
    <%= form.text_field :center, id: :contry_center %>
  </div>

  <div class="field">
    <%= form.label :pop %>
    <%= form.text_field :pop, id: :contry_pop %>
  </div>

  <div class="field">
    <%= form.label :area %>
    <%= form.text_field :area, id: :contry_area %>
  </div>

  <div class="field">
    <%= form.label :money %>
    <%= form.text_field :money, id: :contry_money %>
  </div>

  <div class="field">
    <%= form.label :lang %>
    <%= form.text_field :lang, id: :contry_lang %>
  </div>

  <div class="field">
    <%= form.label :religion %>
    <%= form.text_field :religion, id: :contry_religion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

sudoku/app/views/contries/edit.html.erb
<div class="container">
<h1>Editing Contry</h1>

<%= render 'form', contry: @contry %>

<%= link_to 'Show', @contry %> |
<%= link_to 'Back', contries_path %>
</div>

sudoku/app/views/contries/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>Contries</h1>

<table class="table">
  <thead>
    <tr>
      <th>Continent</th>
      <th>Cont image</th>
      <th>Cont name</th>
      <th>Center</th>
      <th>Pop</th>
      <th>Area</th>
      <th>Money</th>
      <th>Lang</th>
      <th>Religion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contries.each do |contry| %>
      <tr>
        <td><%= contry.continent %></td>
        <td><%= image_tag "#{contry.cont_image}"%></td>
        <td><%= contry.cont_name %></td>
        <td><%= contry.center %></td>
        <td><%= contry.pop %></td>
        <td><%= contry.area %></td>
        <td><%= contry.money %></td>
        <td><%= contry.lang %></td>
        <td><%= contry.religion %></td>
        <td><%= link_to 'Show', contry %></td>
        <td><%= link_to 'Edit', edit_contry_path(contry) %></td>
        <td><%= link_to 'Destroy', contry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contry', new_contry_path %>
</div>

sudoku/app/views/contries/new.html.erb
<div class="container">
<h1>New Contry</h1>

<%= render 'form', contry: @contry %>

<%= link_to 'Back', contries_path %>
</div>

sudoku/app/views/contries/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>Continent:</strong>
  <%= @contry.continent %>
</p>

<p>
  <strong>Cont image:</strong>
  <%= @contry.cont_image %>
</p>

<p>
  <strong>Cont name:</strong>
  <%= @contry.cont_name %>
</p>

<p>
  <strong>Center:</strong>
  <%= @contry.center %>
</p>

<p>
  <strong>Pop:</strong>
  <%= @contry.pop %>
</p>

<p>
  <strong>Area:</strong>
  <%= @contry.area %>
</p>

<p>
  <strong>Money:</strong>
  <%= @contry.money %>
</p>

<p>
  <strong>Lang:</strong>
  <%= @contry.lang %>
</p>

<p>
  <strong>Religion:</strong>
  <%= @contry.religion %>
</p>

<%= link_to 'Edit', edit_contry_path(@contry) %> |
<%= link_to 'Back', contries_path %>
</div>